### ISSUE TITLE
Automate NPM deployment

### ISSUE THREAD

**Issue by SpaghettiC0des** [karlmarxlopez/useStateWithLayoutAnimation#3]
## Task
- [x] Setup Github action for NPM deployment

**Comment by aneeshrelan** [comment]
Can I take this up?

**Comment by SpaghettiC0des** [comment]
Sure! @aneeshrelan

**Comment by aneeshrelan** [comment]
Is the `NPM_AUTH_TOKEN` added to the repo settings? @karlmarxlopez

**Comment by SpaghettiC0des** [comment]
Wait I'll add it @aneeshrelan

**Comment by SpaghettiC0des** [comment]
Done @aneeshrelan

**Comment by aneeshrelan** [comment]
Thanks! @karlmarxlopez . Please excuse me this is my first time trying my hands on Github actions. Putting something up soon!

**Comment by SpaghettiC0des** [comment]
@aneeshrelan No worries! Goodluck!
